### ISSUE TITLE
OMEMO Tracking

### ISSUE THREAD

**Issue by mar-v-in** [dino/dino#36]
This is a feature tracking issue for the OMEMO plug-in. Please report bugs as seperate issues.

- [x] Encrypt/decrypt messages
  - [x] Single user chat
  - [x] Multi user chat (GSoC)
- [x] Display own fingerprint as text in account settings
- [ ] Extended account OMEMO UI
  - [x] Display own fingerprint as text
  - [x] Copy own fingerprint to clipboard
  - [x] Display own fingerprint as QR code (GSoC)
  - [x] Display other devices' keys
  - [x] Un-/trust other devices (GSoC)
  - [ ] Remove devices from own devicelist
- [x] Contact OMEMO UI
  - [x] Display devices' fingerprints as text
  - [x] Un-/trust devices (GSoC)
- [x] Colorize displayed fingerprints to allow easy comparison
- [ ] OMEMO Encrypted Jingle File Transfer (depends on Jingle File Transfers, [current ProtoXEP](https://github.com/siacs/xeps/blob/382c28c40226eb6f734aaf05d9c8aec4a5964adf/inbox/omemo-filetransfer.xml))
- [x] OMEMO Encrypted HTTP File Uploads (ProtoXEP missing)
- [x] Option to disable Blind Trust (GSoC)
- [x] Notify on new own devices (GSoC)

**Comment by mray** [comment]
*Only* colorizing fingerprints can be problematic, better have more contrast than just color, maybe
* font-weight
* size
* brightness
* background
* spacing
* indicator icon
* ...

**Comment by mar-v-in** [comment]
@mray The idea is to colorize in 4 hex character chunks, [similar to OpenKeychain](http://i.imgur.com/W7JWU7J.png) and group 2 chunks together (so that there are 8 groups of 8 characters, which is how OMEMO fingerprints are displayed in Conversations)

**Comment by mray** [comment]
Oh, Ok.  I expected coloring like Gajim does:
![image](https://cloud.githubusercontent.com/assets/164785/25086832/15e35db4-236b-11e7-87e6-df238461b136.png)
The colorizing you have in mind works fine of course.

**Comment by NicoHood** [comment]
I guess image/file sharing is not implemented yet? I got an URL like this: `aesgcm://share.conversations.im/<user>/<a lot of numbers and chars>`

**Comment by NicoHood** [comment]
Can't I receive pictures because its not implemented or because my server does not support it? I think its the first one. Because people send me picture all over and I need to tell them that I cannot decode them because of my client :(

**Comment by mar-v-in** [comment]
If you receive links with `aesgcm://`, this is the non-standard way of conversations to share omemo-encrypted files via http file upload. This is not implemented in Dino yet, neither is Jingle file transfer (which the other client shouldn't even try to use, because support is not announced by Dino). You are able to receive unencrypted or openpgp-encrypted http file uploads though.

**Comment by NicoHood** [comment]
So this means I should open an issue at conversation bugtracker?
Thanks for the information. I will try to send it encrypted then, even though its not the best idea.

**Comment by NicoHood** [comment]
I am willing to donate 50€ to the project if OMEMO gets implemented completely. I wont open any bugbounty program to avoid any additional fees, more for you guys. We will get in touch once its done :)

Keep up the great work!

**Comment by rugk** [comment]
IMHO you should [use this trust model by default](https://gultsch.de/trust.html) as it is also used by Conversations. First "blind trust" and when they are verified (preferably via QR-code scanning), then disable "blind trust" and always show notifications. This is a reasonable trade-off of usability and security IMHO.

**Comment by tdemin** [comment]
@rugk how do you scan a QR code on a desktop computer?

**Comment by rugk** [comment]
On Laptops with webcams that is no problem… But of course you may offer a way for users to manually enter the string for verification or so.

**Comment by tdemin** [comment]
@rugk all the messy ways to compare the codes instead of simply looking at them and tapping "Verified"? No way!

**Comment by rugk** [comment]
Well… QR code scanning is more secure and still convenient… with a webcam… well more or less. Typing manually is not so nice, I agree, but just letting users tap on things labeled "it's ok" is often dangerous. Many many users will not verify anything and just tap things away.

**Comment by tdemin** [comment]
@rugk,
> QR code scanning is more secure

WHAT?

> Many many users will not verify anything and just tap things away.

This only happens if verification is blocking the users from sending messages. The suggested model of trust, if you allow them to compare fingerprints by hand, doesn't bother the users (even doesn't suggest to do anything) and is still OK for the users who can't or don't want to scan codes.

**Comment by rugk** [comment]
> WHAT?

Because of the usability aspect involved. You usually only scan

> This only happens if verification is blocking the users from sending messages. 

Maybe, maybe not. Some users would still verify anything they can – even if it is just to get a green tick…

But yes, I don't say this "click to verify" should not be implemented. It _can_(!) just be dangerous for some users. It could also be "hidden" and only available for users, who know what they do. That's all possible. It just depends on how it is done.

**Comment by tdemin** [comment]
@rugk,
> Because of the usability aspect involved. You usually only scan

Don't mess things up. You say "security" and then speak of usability.

> It can(!) just be dangerous for some users.

Yes! Life is dangerous too, let's save them from living at all!

If the user wants to shoot him(her/it)self in the foot, there's nothing we can do. Such user will eventually shoot out his foot even if every safety system in the world protects him from doing this. And "safeguarding" all the users this way just hurts the ones who simply want to verify themselves with simply comparing codes.

**Comment by rugk** [comment]
> You say "security" and then speak of usability.

Exactly. Because both are very closely connected, nowadays.

And yes, you cannot prevent anybody from doing something insecure. That's not my point. My point is, you have to prevent users from doing insecure things, because they are just users… Users will click through SSL warnings e.g. That's why they are not dismiss-able in modern browsers, depending on the circumstances. 
In many e2e encrypted messengers, users sometimes send the verification code (or however it is called) through the same channel as they want to verify.

With the UI you should discourage that behavior. Make clear it is optional and so on… Or e.g. provide a mechanism, which usually can only be used when the contacts meet in person (that's why I've mentioned QR codes). And yes, if they want, they can screenshot the QR code, send it to the contact, the contact can print them and scan them; but hey… that's the case of shooting in the foot. As a dev you have done everything you can do.

But I think there is not much need to discuss this further. I trust the Dino devs that they do UI+security design etc. correctly. This tickets is about OMEMO, after all, not about "How to design secure systems, which are usable?" 😉

**Comment by wilhelmy** [comment]
Petition to tackle MUC encryption next? :)

**Comment by BadPractice** [comment]
Would you kindly focus down  Un-/trust devices. This is the only think preventing me from using dino :(

**Comment by stevenroose** [comment]
What is the status of encrypted images? gthumb seems to be the only app that can open it and it gives me segfaults on Arch Linux, so I can't open them at all.

Why are sub issues for each separate aspect not allowed?? https://github.com/dino/dino/issues/419

**Comment by albjeremias** [comment]
Is there a bounty for this issue?

**Comment by minils** [comment]
> Is there a bounty for this issue?

https://www.bountysource.com/issues/44025760-omemo-tracking

**Comment by albjeremias** [comment]
Ok... added more 50$ :)

**Comment by devurandom** [comment]
@mar-v-in What is OMEMO v2? Searching the web I can only find rather vague references from a few years ago.

**Comment by NicoHood** [comment]
Encrypted File up/download seems to be supported now:
https://github.com/dino/dino/pull/339#issuecomment-442080497

**Comment by ainola** [comment]
It works well! But I'm getting the fallback message with every picture upload (for conversations, 'I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo').

**Comment by marmistrz** [comment]
> * [x] Option to disable Blind Trust (GSoC)
It shouldn't be marked as done. Currently, there seems to be no way of disabling blind trust globally (or at least it's not hooked to the UI)

**Comment by MrSenshi** [comment]
It seems to me OMEMO has broken. Was working perfectly not long ago. Then it just disappeared when I upgraded. I have compiled it with the OMEMO plugin.

**Comment by wilhelmy** [comment]
> It seems to me OMEMO has broken. Was working perfectly not long ago. Then it just disappeared when I upgraded. I have compiled it with the OMEMO plugin.

I had the same issue when I was running dino from outside the build directory (I didn't make install). If I cd to the build directory, it suc

**Comment by qorg11** [comment]
> Remove devices from own devicelist

Someone is working on that?

**Comment by Neustradamus** [comment]
Good news:
- https://github.com/dino/dino/issues/265#issuecomment-726389726
